double solve1(double x0, int n, double* x, double* y);
double solve2(double x0, int n, double* x, double* y);
double solve3(double x0, int n, double* x, double* y);
double bsin(double x, double epsilon);
double bcos(double x, double epsilon);
double solve5(double x, double epsilon);
double solve6(double x, double epsilon);
double solve7(double x, double epsilon);
double solve8(double x, double epsilon);
int equal(double x, double y);